// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC01IDEttSmLLi3uaCIPaiJxGChzrtoEfs',
    appId: '1:137397725540:web:dfbd1ff14d978c2afa3271',
    messagingSenderId: '137397725540',
    projectId: 'tugasmobile2ar',
    authDomain: 'tugasmobile2ar.firebaseapp.com',
    databaseURL: 'https://tugasmobile2ar-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugasmobile2ar.appspot.com',
    measurementId: 'G-247D5PJL4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXNLX5hY-dhZZxSwLDfdM8UWklktQiwOI',
    appId: '1:137397725540:android:2db2b0de5c2f2859fa3271',
    messagingSenderId: '137397725540',
    projectId: 'tugasmobile2ar',
    databaseURL: 'https://tugasmobile2ar-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugasmobile2ar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr0H4NM3WQO56kEeUpP5lnYrit6uF_lN0',
    appId: '1:137397725540:ios:17fb8f7cca464fb2fa3271',
    messagingSenderId: '137397725540',
    projectId: 'tugasmobile2ar',
    databaseURL: 'https://tugasmobile2ar-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugasmobile2ar.appspot.com',
    iosBundleId: 'com.example.authMobile2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr0H4NM3WQO56kEeUpP5lnYrit6uF_lN0',
    appId: '1:137397725540:ios:17fb8f7cca464fb2fa3271',
    messagingSenderId: '137397725540',
    projectId: 'tugasmobile2ar',
    databaseURL: 'https://tugasmobile2ar-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugasmobile2ar.appspot.com',
    iosBundleId: 'com.example.authMobile2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC01IDEttSmLLi3uaCIPaiJxGChzrtoEfs',
    appId: '1:137397725540:web:bc5d8d7bc15ebee0fa3271',
    messagingSenderId: '137397725540',
    projectId: 'tugasmobile2ar',
    authDomain: 'tugasmobile2ar.firebaseapp.com',
    databaseURL: 'https://tugasmobile2ar-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugasmobile2ar.appspot.com',
    measurementId: 'G-S2FKQ1BPB5',
  );
}
